name: Typst Compile and Push Output

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted  # Ensure this matches your self-hosted runner labels

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full history is fetched for pushing

      # 2. Debug: Print PATH and Typst Version
      - name: Debug Environment
        run: |
          echo "Current PATH: $PATH"
          which typst || echo "Typst not found in PATH"
          typst --version || echo "Typst version check failed"

      # 3. Add /usr/local/bin to PATH if not already present
      - name: Ensure /usr/local/bin is in PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      # 4. Verify Typst Accessibility
      - name: Verify Typst Accessibility
        run: |
          which typst
          typst --version

      # 5. Make compile.sh executable (if not already executable)
      - name: Make compile.sh executable
        run: chmod +x ./compile.sh

      # 6. Set up Git user for committing
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 7. Run the compile script
      - name: Run compile.sh
        run: ./compile.sh

      # 8. Add Changes to Git
      - name: Add Changes
        run: git add -f output

      # 9. Commit Changes
      - name: Commit Changes
        run: |
          git commit -m "Update output files [skip ci]" || echo "No changes to commit."

      # 10. Push Changes to Repository
      - name: Push Changes
        run: git push origin main || echo "No changes to push."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy files to Syncthing Dir
        run: cp ./output/*.pdf /home/runner/Sync/resume